In [1]:
from tensorflow.keras.models import load_model
import numpy as np
import cv2

In [6]:
model=load_model('testmodel2.h5')

In [11]:
from skimage.transform import resize

In [12]:
def detect(frame):
    try:
        img = resize(frame,(64,64))
        #print("dim",img)
        img = np.expand_dims(img,axis=0)
        print("dim2",img)
        if(np.max(img)>1):
            img= img/255.0
        prediction=model.predict(img)
        print(prediction)
        print(model.predict_classes(img))
    except AttributeError:
        print("Shape Not Found")

In [13]:
frame=cv2.imread(r'/home/manikanta/internship/natural_images/test_set/airplane/airplane_0572.jpg')
data=detect(frame)

dim2 [[[[0.75080399 0.60784314 0.4745098 ]
   [0.75903799 0.60884579 0.47668505]
   [0.74944853 0.6064951  0.47316176]
   ...
   [0.82745098 0.66666667 0.53333333]
   [0.82570466 0.66766932 0.53158701]
   [0.82352941 0.66666667 0.52941176]]

  [[0.74354392 0.60807986 0.4745098 ]
   [0.74910601 0.60784314 0.4745098 ]
   [0.71556875 0.59024299 0.45690966]
   ...
   [0.82745098 0.66666667 0.53333333]
   [0.82352941 0.66666667 0.52941176]
   [0.82352941 0.66666667 0.52941176]]

  [[0.7372549  0.61176471 0.4745098 ]
   [0.74329044 0.61125512 0.47580782]
   [0.60325425 0.49161377 0.36621381]
   ...
   [0.82745098 0.66666667 0.53333333]
   [0.82745098 0.66666667 0.53333333]
   [0.82745098 0.66666667 0.53333333]]

  ...

  [[0.72886676 0.61514127 0.49341299]
   [0.73514093 0.62141544 0.49984681]
   [0.7372549  0.62352941 0.50196078]
   ...
   [0.80088848 0.65490196 0.5372549 ]
   [0.80392157 0.65490196 0.5372549 ]
   [0.80392157 0.65490196 0.5372549 ]]

  [[0.7254902  0.61176471 0.49019608]
  

In [14]:
frame=cv2.imread(r'/home/manikanta/internship/natural_images/test_set/car/car_0803.jpg')
data=detect(frame)

dim2 [[[[1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   ...
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]]

  [[1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   ...
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]]

  [[1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   ...
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]]

  ...

  [[0.99607843 0.99607843 0.99607843]
   [0.99607843 0.99607843 0.99607843]
   [0.99767157 0.99607843 0.99767157]
   ...
   [0.99310279 0.99310279 0.99310279]
   [0.99215686 0.99215686 0.99215686]
   [0.99215686 0.99215686 0.99215686]]

  [[1.         1.         1.        ]
  

In [29]:
frame=cv2.imread(r'/home/manikanta/internship/natural_images/test_set/cat/cat_0882.jpg')
data=detect(frame)

dim2 [[[[0.41200143 0.33465074 0.36994485]
   [0.40854229 0.33722977 0.37322304]
   [0.41890319 0.35442301 0.39859069]
   ...
   [0.46878064 0.41387868 0.45020321]
   [0.48627451 0.42352941 0.45882353]
   [0.48556985 0.42745098 0.45811887]]

  [[0.39879964 0.32620036 0.36541604]
   [0.39425432 0.3254902  0.36078431]
   [0.41121324 0.34761029 0.38434125]
   ...
   [0.41841299 0.4        0.44411454]
   [0.46096814 0.41568627 0.43924632]
   [0.47794118 0.41780025 0.45309436]]

  [[0.39057498 0.31372549 0.35920243]
   [0.39957108 0.32506127 0.36470277]
   [0.40352328 0.33698419 0.37647059]
   ...
   [0.35566789 0.42251838 0.50245098]
   [0.45101103 0.41179534 0.44705882]
   [0.46534926 0.41436887 0.45358456]]

  ...

  [[0.5014287  0.49984681 0.50927184]
   [0.49764404 0.49724576 0.51293203]
   [0.50561164 0.49916777 0.51724877]
   ...
   [0.51093247 0.52269718 0.54469975]
   [0.51375613 0.52552083 0.55257664]
   [0.5254902  0.5372549  0.56470588]]

  [[0.52428984 0.53012193 0.53936887]
  

In [16]:
frame=cv2.imread(r'/home/manikanta/internship/natural_images/test_set/dog/dog_0584.jpg')
data=detect(frame)

dim2 [[[[0.05753676 0.40392157 0.48498775]
   [0.05658701 0.39221814 0.47064951]
   [0.04454657 0.34295343 0.39926471]
   ...
   [0.00784314 0.13051471 0.18370816]
   [0.00952819 0.10551471 0.1563376 ]
   [0.         0.00906863 0.01875144]]

  [[0.07208946 0.40747118 0.4890625 ]
   [0.07331495 0.39731685 0.47467592]
   [0.05809733 0.29702484 0.37404689]
   ...
   [0.00784314 0.12941176 0.17650123]
   [0.01450913 0.10142703 0.14438046]
   [0.         0.00294548 0.00906863]]

  [[0.07637868 0.41568627 0.49302189]
   [0.07918821 0.35529115 0.42201909]
   [0.0773337  0.34745711 0.4205576 ]
   ...
   [0.0057038  0.09380601 0.12716998]
   [0.02335468 0.07846201 0.10694556]
   [0.         0.00392157 0.00257353]]

  ...

  [[0.19214968 0.09597934 0.05566789]
   [0.15921272 0.06954657 0.03539848]
   [0.15042892 0.07058824 0.03336397]
   ...
   [0.29527133 0.27945724 0.32231876]
   [0.30917873 0.18477328 0.14209559]
   [0.2810049  0.14503676 0.09347426]]

  [[0.16794912 0.07827819 0.03830088]
  

In [17]:
frame=cv2.imread(r'/home/manikanta/internship/natural_images/test_set/flower/flower_0719.jpg')
data=detect(frame)

dim2 [[[[0.05490196 0.11372549 0.08235294]
   [0.06666667 0.11764706 0.08627451]
   [0.07778177 0.13900745 0.10055147]
   ...
   [0.06661162 0.19139715 0.15816196]
   [0.11522672 0.37962862 0.2856948 ]
   [0.1317402  0.41742159 0.30248162]]

  [[0.05882353 0.11844123 0.08627451]
   [0.07052696 0.12787272 0.09411765]
   [0.08627451 0.13976716 0.10196078]
   ...
   [0.0510723  0.13443627 0.12659314]
   [0.05256635 0.19923407 0.15683211]
   [0.09675245 0.37931985 0.27472426]]

  [[0.05882353 0.1263849  0.09331486]
   [0.07449113 0.1754902  0.13232901]
   [0.08235294 0.18367034 0.1338848 ]
   ...
   [0.04705882 0.12374339 0.11240809]
   [0.04319853 0.11000641 0.09816176]
   [0.11626838 0.33814338 0.26301461]]

  ...

  [[0.1698223  0.4208027  0.32588226]
   [0.13704044 0.39198501 0.29270833]
   [0.07089509 0.31228554 0.22775783]
   ...
   [0.08495711 0.42221201 0.30848652]
   [0.1254902  0.43005515 0.3203125 ]
   [0.10285549 0.39096201 0.29684436]]

  [[0.19022911 0.45297421 0.34659926]
  

In [20]:
frame=cv2.imread(r'/home/manikanta/internship/natural_images/test_set/fruit/fruit_0803.jpg')
data=detect(frame)

dim2 [[[[1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   ...
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]]

  [[1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   ...
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]]

  [[1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   ...
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]]

  ...

  [[0.98782552 1.         0.9932598 ]
   [0.99165901 1.         0.99607843]
   [0.99767157 0.99607843 1.        ]
   ...
   [1.         1.         0.99607843]
   [1.         1.         1.        ]
   [1.         1.         1.        ]]

  [[0.99431296 1.         1.        ]
  

In [19]:
frame=cv2.imread(r'/home/manikanta/internship/natural_images/test_set/motorbike/motorbike_0664.jpg')
data=detect(frame)

dim2 [[[[0.2111826  0.2229473  0.16412377]
   [0.23027057 0.24203527 0.18076172]
   [0.21382602 0.22559072 0.1624866 ]
   ...
   [0.16576095 0.17335038 0.08732958]
   [0.12931985 0.13924537 0.04690372]
   [0.16909658 0.17693972 0.09061447]]

  [[0.17086493 0.18262963 0.1238061 ]
   [0.20376551 0.21458046 0.15679573]
   [0.18127585 0.19304056 0.13516678]
   ...
   [0.15964595 0.15884459 0.08136297]
   [0.12574391 0.12479416 0.04253025]
   [0.13424958 0.14206304 0.05578853]]

  [[0.15751953 0.16536267 0.11831246]
   [0.18743394 0.19465954 0.14851984]
   [0.1646628  0.16858437 0.12599858]
   ...
   [0.15743241 0.14572898 0.07630496]
   [0.11863224 0.11347561 0.03568761]
   [0.14066425 0.13673407 0.0583027 ]]

  ...

  [[0.17194968 0.07366536 0.10879768]
   [0.18360428 0.05762868 0.11209693]
   [0.21856618 0.08192402 0.14867685]
   ...
   [0.09257334 0.01087623 0.02207127]
   [0.11271446 0.01208065 0.03827072]
   [0.11062251 0.00038967 0.0352855 ]]

  [[0.15315659 0.04800858 0.09326076]
  

In [27]:
frame=cv2.imread(r'/home/manikanta/internship/natural_images/test_set/person/person_0914.jpg')
data=detect(frame)

dim2 [[[[0.21568627 0.19607843 0.16078431]
   [0.21568627 0.19607843 0.16078431]
   [0.21568627 0.19607843 0.16078431]
   ...
   [0.33039216 0.34509804 0.3254902 ]
   [0.35686275 0.36764706 0.35098039]
   [0.36764706 0.39117647 0.37156863]]

  [[0.21568627 0.19607843 0.16078431]
   [0.21568627 0.19607843 0.16078431]
   [0.21568627 0.19607843 0.16078431]
   ...
   [0.40196078 0.42254902 0.40294118]
   [0.32647059 0.33823529 0.32156863]
   [0.34117647 0.35882353 0.33921569]]

  [[0.21568627 0.19607843 0.16078431]
   [0.21372549 0.19411765 0.15882353]
   [0.21372549 0.19411765 0.15882353]
   ...
   [0.45392157 0.4872549  0.46666667]
   [0.36176471 0.38235294 0.3627451 ]
   [0.32843137 0.34509804 0.3254902 ]]

  ...

  [[0.20784314 0.19509804 0.15686275]
   [0.20784314 0.19411765 0.15686275]
   [0.20784314 0.19411765 0.15686275]
   ...
   [0.38627451 0.4372549  0.44509804]
   [0.36372549 0.41470588 0.42254902]
   [0.37352941 0.4245098  0.43235294]]

  [[0.20294118 0.19607843 0.15686275]
  